Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@Leandro-VS 
andresionek91
/
bootcamp-turma-5-data-platform
1
21
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
bootcamp-turma-5-data-platform/.github/workflows/deploy_production.yml
@andresionek91
andresionek91 muda nome do bucket
Latest commit f84b30e 5 hours ago
 History
 1 contributor
38 lines (31 sloc)  836 Bytes
 
name: Deploy Data Platform to Production

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Install dependencies
      run: |
        npm install -g aws-cdk
        pip install -r requirements.txt
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        ENVIRONMENT: PRODUCTION
      run: |
        cdk bootstrap
        cdk deploy "*" --require-approval never